language: go

go:
  - 1.0.x
  - 1.1.x
  # - 1.2.x There is a known Timeout error in http.Client. Skipping builds.
  # - 1.3.x There is an error in Travis env while using logrus for testing.
  # - 1.4.x 
  # - 1.5.x
  # - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - master

before_script:
  - go get github.com/google/go-querystring/query
  - go get github.com/sirupsen/logrus
  - go get github.com/stretchr/testify/assert

script: go test ./... -v
